Performance improvement: WebPへの対応
codeforsapporo/covid19 pull request #407
Opened 2020-04-24 09:49 UTC by Nekoya3

## 📝 関連issue

- #402 

## ⛏ 変更内容

- 画像形式をWebPに変更

## 📸 スクリーンショット

2020-04-24 12:11 UTC, daisuke-fukuda requested changes
レイアウト崩れています

<img width="305" alt="スクリーンショット 2020-04-24 21 10 35" src="https://user-images.githubusercontent.com/32258949/80211153-24cb8c00-8670-11ea-82c5-6cece007c704.png">

2020-04-24 12:11 UTC, daisuke-fukuda commented on assets/locales/ja.i18n.json
> +  "Under": "Under",
これはこの変更とはどういった関係ですか？

2020-04-24 12:11 UTC, daisuke-fukuda commented on components/SideNavigation.vue
> +            <p style="margin-bottom: 0 !important;">{{ $t('Under') }}</p>
あまり `important` 使いたくないですが、どうしても必要でしょうか

2020-04-24 12:12 UTC, daisuke-fukuda commented on components/SideNavigation.vue
> +                srcset="/twitter.webp"
全体的にパラメータが冗長になるので、component作っちゃうのはいかがでしょうか

2020-04-24 14:03 UTC, Nekoya3 commented on components/SideNavigation.vue
> +                srcset="/twitter.webp"
ですね。そうします！

2020-04-24 14:23 UTC, Nekoya3 commented on assets/locales/ja.i18n.json
> +  "Under": "Under",
<i18n>タグでくくってたんですが、ImageとImageTitleをi18n対応する必要がないのでこうしたんですが、コンポーネントに変えるので戻せないかやってみます

2020-04-25 07:40 UTC, Nekoya3 commented on assets/locales/ja.i18n.json
> +  "Under": "Under",
変えずに修正可能だったのでrevertしてます

2020-04-25 08:19 UTC, daisuke-fukuda commented on components/VPicture.vue
> +<template>
VPictureという名前は

- vuetifyのコンポーネントっぽい
- 他のコンポーネントと命名規則があっていない（Vとつけてるやつはいない）

のでイマイチだと思います。

2020-04-25 08:30 UTC, Nekoya3 commented on components/VPicture.vue
> +<template>
PictureLoaderにコンポーネント名を変更しました

2020-04-27 04:51 UTC, daisuke-fukuda approved these changes
念の為ブラウザのクロスチェックを注意していリリースしましょう

2020-04-28 19:19 UTC, Nekoya3 commented
確認完了のためマージ

2020-04-28 19:23 UTC, merged